name: task_in_v2
description: A community service application targeting rural and tier-2 cities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  flame: ^1.14.0
  url_launcher: ^6.1.14
  lottie: ^2.7.0
  geolocator: ^10.1.0
  map_launcher: ^3.1.0
  geocoding: ^2.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/